castai/terraform-provider-castai

castai/config.go
castai/provider.go
castai/sdk/spec.yaml
examples/localdev/main.tf.sample

V1 of API is now prefixed with `/v1` in the path, and serving API from root will be dropped in the future.

switch to V1 path for API

---

README.md

Docs: Provider configuration requires api_token

---

castai/resource_rebalancing_job_test.go
castai/resource_rebalancing_schedule.go
castai/resource_rebalancing_schedule_test.go
castai/sdk/api.gen.go
castai/utils.go
docs/resources/rebalancing_schedule.md
examples/eks/eks_cluster_autoscaler_polices/castai.tf
examples/resources/castai_rebalancing_schedule/resource.tf

The execution conditions define conditions that must be met during the execution of the plan in order for it to run until the end. 
For example, if the execution conditions are enabled but the percentage of achieved savings is not met when the new nodes are created, the rebalancing plan will not proceed further and will rollback the created nodes. This is specially useful when, initially, the rebalancing plan predicts X% of savings, but due to certain constraints, that are known during the runtime, like unavailability of instance types, it creates instance types that are pricier than predicted.
In this MR, the execution conditions allow to control the minimum % of the predicted savings that must be achieved in order to continue with the rebalancing plan.

CO-2326: Add the execution conditions to the scheduled rebalancing

---

castai/sdk/api.gen.go
examples/aks/aks_cluster_read_only/README.MD
examples/aks/aks_cluster_read_only/aks.tf
examples/aks/aks_cluster_read_only/castai.tf
examples/aks/aks_cluster_read_only/providers.tf
examples/aks/aks_cluster_read_only/tf.vars.example
examples/aks/aks_cluster_read_only/variables.tf
examples/aks/aks_cluster_read_only/versions.tf

Add a read-only example for customers

Add R/O Onboarding example for AKS

---

castai/sdk/api.gen.go
examples/aks/aks_cluster_arm_template/README.MD
examples/aks/aks_cluster_arm_template/aks.tf
examples/aks/aks_cluster_arm_template/castai.tf
examples/aks/aks_cluster_arm_template/castai_arm_template.json
examples/aks/aks_cluster_arm_template/providers.tf
examples/aks/aks_cluster_arm_template/tf.vars.example
examples/aks/aks_cluster_arm_template/variables.tf
examples/aks/aks_cluster_arm_template/versions.tf
examples/aks/aks_cluster_arm_template/vnet.tf
examples/aks/aks_cluster_read_only/README.MD
examples/aks/aks_cluster_read_only/aks.tf
examples/aks/aks_cluster_read_only/castai.tf
examples/aks/aks_cluster_read_only/providers.tf
examples/aks/aks_cluster_read_only/tf.vars.example
examples/aks/aks_cluster_read_only/variables.tf
examples/aks/aks_cluster_read_only/versions.tf

Add support for onboarding the CAST AI component of AKS using an ARM template.

Aks arm template

---

examples/eks/eks_cluster_existing/castai.tf
examples/eks/eks_cluster_existing/providers.tf
examples/eks/eks_cluster_existing/variables.tf

This is to give the end user the possibility to use a different AWS Profile value other than 'default' and avoiding the use of 
`export AWS_DEFAULT_PROFILE=my-profile-xyz`
Otherwise, one might get the following error: `Error: Kubernetes cluster unreachable: the server has asked for the client to provide credentials`

Added aws profile variable when trying to install cast.ai using the eks_cluster_existing example

---

examples/aks/aks_cluster/README.MD
examples/aks/aks_cluster_arm_template/README.MD
examples/aks/aks_cluster_autoscaler_policies/README.MD
examples/aks/aks_cluster_azure_cni/README.MD
examples/aks/aks_cluster_existing/README.MD
examples/aks/aks_cluster_read_only/README.MD
examples/eks/eks_cluster_assumerole/README.MD
examples/eks/eks_cluster_autoscaler_policies/README.MD
examples/eks/eks_cluster_custom_iam/README.md
examples/eks/eks_cluster_existing/README.MD
examples/eks/eks_cluster_optional_readonly/README.MD
examples/eks/eks_cluster_readonly/README.MD
examples/gke/evictor_advanced_config/README.MD
examples/gke/gke_castai_iam/README.md
examples/gke/gke_cluster_autoscaler_policies/README.MD
examples/gke/gke_cluster_existing/README.MD
examples/gke/gke_cluster_readonly/README.MD
examples/gke/gke_cluster_zonal_autoscaler/README.MD

Updated README in Example repos to add TF t-shooting guide

Updated README in Example repos

---

castai/const.go
castai/resource_node_template.go
castai/resource_node_template_test.go
docs/resources/node_template.md

Deprecate `compute_optimized` and `storage_optimized` constraints and introduce `compute_optimized_status` and `storage_optimized_status` to allow empty values

refactor!: deprecate `compute_optimized` and `storage_optimized` contraints

---

examples/eks/eks_cluster_autoscaler_policies/castai.tf
examples/eks/eks_cluster_existing/castai.tf
examples/eks/eks_cluster_webshop/main.tf
examples/eks/eks_clusters/module/castai/castai.tf

Depends on https://github.com/castai/terraform-castai-eks-cluster/pull/92

refactor: use `autoscaler_policy_overrides` in examples for eks

---

examples/aks/aks_cluster_arm_template/castai.tf
examples/aks/aks_cluster_autoscaler_policies/castai.tf
examples/aks/aks_cluster_existing/castai.tf

Depends on https://github.com/castai/terraform-castai-aks/pull/64

refactor: use `autoscaler_policy_overrides` in examples for aks

---

castai/resource_node_configuration.go
castai/resource_node_configuration_eks_test.go
docs/resources/node_configuration.md

Allows user to select a family of images that determines bootstrap logic and (potentially) VM image choice

KUBE-328: Support setting image family on node configuration 

---

castai/resource_node_configuration.go
castai/resource_node_configuration_test.go
castai/sdk/api.gen.go
docs/resources/node_configuration.md

In TF state remains the same but we remove the 1 item restriction. 
Old TF version uses old field (backend ensures it is appended to new field on post). 
New TF version uses only new field.
Note that using an old TF version and new version to edit the same config will result in data overwrite and will not be supported.

KUBE-447: Support multiple target groups per node configuration

---

castai/resource_node_template.go
castai/resource_node_template_test.go
castai/sdk/api.gen.go

Before this commit, there was a difference
in how the SDK and the Terraform provider render the K8s Operator `In`. The SDK returned uppercase `IN`, while the Terraform provider expected `In`. This led to Terraform showing a difference in an infrastructure's state even when there was none.
This commit maps SDK Operator values to those defined in the provider.

fix: map SDK NodeAffinity operators to canonical provider values

---

Makefile
castai/resource_organization_members.go
castai/sdk/api.gen.go
castai/sdk/generate.go

Make generator bit more flexible so we can pre-validate changes from outside the repo.

NOJIRA: make sdk generation external pluggable/configurable & regenate SDK

---

castai/resource_autoscaler.go
castai/resource_autoscaler_test.go
castai/types/autoscaler_policies.go
docs/resources/autoscaler.md

This commit adds Pod Pinner to the provider. Since Pod Pinner is enabled (`true`) by default, and we don't care if it is not set in Terraform, It is implemented as a boolean value instead of a tri-state toggle.

CO-3070: feat: add pod pinner

---

examples/gke/gke_cluster_autoscaler_policies/gke.tf
examples/gke/gke_cluster_autoscaler_policies/variables.tf
examples/gke/gke_cluster_autoscaler_policies/vpc.tf

Also set default `cluster_zones = []`, so if none provided, all in the region will be used.

chore: update modules in gke_cluster_autoscaler_policies

---

castai/resource_organization_members.go
castai/sdk/api.gen.go
castai/sdk/client.gen.go
castai/sdk/mock/client.go

This PR fixes the below panic in `resource_organization_members`.
I found it while testing the provider against RBACv2 changes.
```
Stack trace from the terraform-provider-castai plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1010d8df0]
goroutine 43 [running]:
github.com/castai/terraform-provider-castai/castai.resourceOrganizationMembersRead({0x101426ea0, 0x14000254930}, 0x14000276d80, {0x1012968e0?, 0x140002bc058?})
/Users/radosny/projects/terraform-provider-castai/castai/resource_organization_members.go:177 +0x7d0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x1400043db20, {0x101426df8, 0x140004d7b30}, 0x14000276d80, {0x1012968e0, 0x140002bc058}) …
```

fix: list invitations response check

---

examples/eks/eks_cluster_gitops/README.md
examples/gke/gke_cluster_existing/castai.tf
examples/gke/gke_cluster_gitops/castai.tf

Summary:
1. custom_instances_enabled = true needs to be added in unschedulable_pods policy
2. Readme instance profile name fix

Add depreciated field for backward compatibility

---

castai/resource_aks_cluster.go
castai/resource_aks_cluster_test.go

**Problem**
Observed issues when a customer "updated" credentials for a cluster but the update failed. Afterwards customer was stuck - terraform had stale credentials in state but thought they match what Cast had on SaaS side. 
Observed symptomps:
- After failed update, Terraform does not detect drift anymore so it will not attempt to re-apply the credentials. User has to manually reset credentials to trigger re-apply. Makes for bad UX. 
- Even remotely resetting the credentials does not work as `credentials_id` differences have no effect on plan since it's computed. 
-  Failed update was stuck until context deadline exceeded, showing no info on _what_ failed for debugging (without setting `TF_LOG`). 
For now, we decided not to expose credentials hash in API until it is 100% required so …

CSU-2424: AKS drift detection improvements 

---

Makefile
castai/cluster.go
castai/resource_aks_cluster.go
castai/resource_aks_cluster_test.go
castai/resource_eks_cluster.go
castai/resource_eks_cluster_test.go
castai/resource_gke_cluster.go
castai/resource_gke_cluster_test.go
castai/sdk/api.gen.go

Similar logic to https://github.com/castai/terraform-provider-castai/pull/422 but for GKE and EKS. Unified some logic (mostly retry and drift) in one method. 
For EKS, there is no "drift" on Read because assumeRole is already exposed so we don't need detection - it is handled automatically. 
This means long-term (as we move to 100% impersonation on all clouds), the drift detection will not be needed.

CSU-2024: Drift detection for other clouds

---

castai/resource_workload_scaling_policy.go
castai/resource_workload_scaling_policy_test.go
castai/sdk/api.gen.go
castai/sdk/client.gen.go
castai/sdk/mock/client.go
docs/resources/workload_scaling_policy.md
examples/resources/castai_workload_scaling_policy/resource.tf

**Description**
- Add support for setting cpu&mem limit strategy
https://github.com/user-attachments/assets/bc74b973-c5d9-4e12-b357-a157703346a7

Add support for setting cpu&mem limit strategy

---

examples/aks/aks_cluster_gitops/README.md
examples/eks/eks_cluster_gitops/README.md
examples/eks/eks_cluster_gitops/outputs.tf
examples/gke/gke_cluster_gitops/README.md

Note:
cluster token output (examples/eks/eks_cluster_gitops/outputs.tf) will not display token during TF apply.
Its needed to collect token & pass it to deploy via agrocd in gitops approach

Update readme to use cluster token for gitops

---

castai/cluster.go
castai/provider.go
castai/resource_aks_cluster.go
castai/resource_autoscaler.go
castai/resource_eks_cluster.go
castai/resource_gke_cluster.go
castai/resource_organization_group.go
castai/resource_rebalancing_job.go
castai/resource_rebalancing_schedule.go
castai/resource_role_bindings.go
castai/sdk/api.gen.go
castai/sdk/client.gen.go
castai/sdk/codegen/templates/client-with-responses.tmpl
castai/sdk/mock/client.go

This PR introduces the following changes: 
- Embed SDK's `ClientInterface` into `ClientWithResponsesInterface` 
- Use `ClientWithResponsesInterface` interface in `ProviderConfig` instead of concrete `*sdk.ClientWithResponses` type
This makes testing easier as we're no longer limited to response-less API calls, for example:
```go
ctrl := gomock.NewController(t)
mockClient := mock_sdk.NewMockClientWithResponsesInterface(ctrl)
provider := &ProviderConfig{
api: &sdk.ClientWithResponses{
ClientInterface: mockClient,
},
}
// Calling EXPECT() is now possible for both WithResponse and "response-less" methods
mockClient.EXPECT().UsersAPIListOrganizations(gomock.Any())
mockClient.EXPECT().UsersAPIListOrganizationsWithResponse(gomock.Any())
provider.api.UsersAPIListOrganizations(ctx) …
```

chore: SDK API client improvements

---

castai/resource_workload_scaling_policy.go
castai/sdk/api.gen.go
docs/resources/workload_scaling_policy.md
templates/resources/workload_scaling_policy.md.tmpl

**Description**
This PR allows to manage default scaling policies without importing them. If there is create operation against the default scaling policy, it's changed to update.
Without this PR, the following error is thrown:
```tf
╷
│ Error: expected status code 200, received: status=409 body={"message":"scaling policy with the same name already exists", "fieldViolations":[]}
│
│   with castai_workload_scaling_policy.default["staging"],
│   on import.tf line 8, in resource "castai_workload_scaling_policy" "default":
│    8: resource "castai_workload_scaling_policy" "default" {
╵
```
I also update the import section to describe easier way of doing that.
**Limitations**
1. Default policies are created in the context of a given cluster ID. As a result, you need to collect and provide all …

Handle the creation of default scaling policies

---

castai/resource_aks_cluster.go
castai/resource_aks_cluster_test.go
castai/sdk/api.gen.go
castai/sdk/client.gen.go
castai/sdk/mock/client.go
docs/resources/aks_cluster.md

Used in scenarios where cluster egress communication must go through proxy. Configures our log sender, bootstrap checker, init data to use that proxy. Does not configure cluster components (this is doable via helm values).

KUBE-856: Add http proxy settings to AKS 

---

castai/resource_workload_scaling_policy.go
castai/resource_workload_scaling_policy_test.go
castai/sdk/api.gen.go
castai/sdk/client.gen.go
castai/sdk/mock/client.go
docs/resources/workload_scaling_policy.md
examples/resources/castai_workload_scaling_policy/resource.tf

There was one issue with TF sdk being unable to recognize unset and zero values. Kube team recommended setting value to string. 
- I had to rework how validation works - the denominator in req is float and not pointer, so I would have to map it to 
-1 or something like that, or validate it during mapping
- I choose to validate it during mapping, too me it seems as much cleaner way how to do it, instead of validating req struct
- Because of that I also had to change tests a little bit
```terraform
resource "castai_workload_scaling_policy" "xyz" {
name              = "xyz"
cluster_id        = "68f9f4ce-6910-4e66-a545-b32f93a4638f"
apply_type        = "IMMEDIATE"
management_option = "MANAGED"
cpu {
apply_threshold_strategy {
type        = "CUSTOM_ADAPTIVE"
numerator   = 0.4
denominator = 0.3 …
```

feat: add adaptive threshold

---

castai/sdk/api.gen.go
castai/sdk/client.gen.go
castai/sdk/mock/client.go
examples/aks/aks_cluster_with_proxy/README.MD
examples/aks/aks_cluster_with_proxy/aks.tf
examples/aks/aks_cluster_with_proxy/castai.tf
examples/aks/aks_cluster_with_proxy/data.tf
examples/aks/aks_cluster_with_proxy/egress_firewall.tf
examples/aks/aks_cluster_with_proxy/network.tf
examples/aks/aks_cluster_with_proxy/providers.tf
examples/aks/aks_cluster_with_proxy/proxy_firewall.tf
examples/aks/aks_cluster_with_proxy/tf.vars.example
examples/aks/aks_cluster_with_proxy/variables.tf
examples/aks/aks_cluster_with_proxy/versions.tf

This is mostly to show how to use (and test) the HTTP proxy functionality as it is not always obvious how to configure an AKS cluster with proxy setup.

KUBE-856: Add example that deploys cluster which requires proxy.

---

go.mod
go.sum

chore: switch to go 1.22.0 as higher version causes incompatibilities
and downgrade `github.com/hashicorp/terraform-plugin-docs` to v0.19.4 as higher versions require go 1.22.7

chore: switch to go1.22 and downgrade github.com/hashicorp/terraform-plugin-docs

---

castai/data_source_resource_rebalancing_schedule_test.go
castai/resource_rebalancing_schedule.go
castai/resource_rebalancing_schedule_test.go
castai/sdk/api.gen.go
docs/data-sources/rebalancing_schedule.md
docs/resources/rebalancing_schedule.md

This PR adds support for an updated granular aggressive mode config in scheduled rebalancing. We intend to replace the legacy bool-based `aggressiveMode` flag by this config.

feat: support granular aggressive mode config

---

Makefile
castai/resource_gke_cluster_id.go
castai/resource_gke_cluster_id_test.go

Read from get cluster rewrite created cast_service_account, which causes _terraform apply_ to fail on the second run.

KUBE-766: bugfix: cast_service_account on read

---

castai/data_source_resource_rebalancing_schedule_test.go
castai/resource_node_configuration.go
castai/resource_rebalancing_schedule_test.go
castai/sdk/api.gen.go
castai/sdk/client.gen.go
castai/sdk/mock/client.go

This PR:
* fixes breakages after latest updates to the SDK
* addresses comments after approving #465 458.

chore: fix SDK change, improve style and tests in scheduled rebalancing found after approving previous PR

---

castai/resource_aks_cluster.go
castai/resource_eks_cluster.go
castai/resource_gke_cluster.go
castai/sdk/api.gen.go
castai/sdk/client.gen.go
examples/aks/aks_cluster_with_security/README.MD
examples/aks/aks_cluster_with_security/aks.tf
examples/aks/aks_cluster_with_security/castai.tf
examples/aks/aks_cluster_with_security/providers.tf
examples/aks/aks_cluster_with_security/tf.vars.example
examples/aks/aks_cluster_with_security/variables.tf
examples/aks/aks_cluster_with_security/versions.tf
examples/aks/aks_cluster_with_security/vnet.tf
examples/eks/eks_cluster_with_security/README.MD
examples/eks/eks_cluster_with_security/castai.tf
examples/eks/eks_cluster_with_security/eks.tf
examples/eks/eks_cluster_with_security/providers.tf
examples/eks/eks_cluster_with_security/tf.vars.example
examples/eks/eks_cluster_with_security/variables.tf
examples/eks/eks_cluster_with_security/versions.tf
examples/eks/eks_cluster_with_security/vpc.tf
examples/gke/gke_cluster_with_security/README.MD
examples/gke/gke_cluster_with_security/castai.tf
examples/gke/gke_cluster_with_security/gke.tf
examples/gke/gke_cluster_with_security/providers.tf
examples/gke/gke_cluster_with_security/tf.vars.example
examples/gke/gke_cluster_with_security/variables.tf
examples/gke/gke_cluster_with_security/version.tf
examples/gke/gke_cluster_with_security/vpc.tf

Adding security examples

---

castai/resource_node_template.go
castai/resource_node_template_test.go
castai/sdk/api.gen.go
docs/resources/node_template.md

example configuration:
```
resource "castai_node_template" "gpu_sharing" {
cluster_id = castai_eks_clusterid.cluster_id.id
name             = "gpu_sharing"
is_default       = false
is_enabled       = true
configuration_id = "32354e7c-adac-4b7a-b82f-cdafaf86a4ab"
should_taint     = false
constraints {
on_demand = true
}
gpu {
default_shared_clients_per_gpu = 5
enable_time_sharing            = true
sharing_configuration {
gpu_name = "L4"
shared_clients_per_gpu = 8
}
sharing_configuration {
gpu_name = "L5"
shared_clients_per_gpu = 2
}
sharing_configuration {
gpu_name = "Tesla T4"
shared_clients_per_gpu = 4
}
}
}
```
Related changes in terraform module for EKS: https://github.com/castai/terraform-castai-eks-cluster/pull/128

feat: add GPU sharing settings to Node Template

---

castai/resource_node_template.go
castai/sdk/api.gen.go
castai/sdk/client.gen.go

fix: set nil when gpu configuration is empty instead of zero-values
when zero-values are set API validation blocks request

fix: set nil when gpu configuration is empty

---

examples/eks/eks_live_migration/README.md
examples/eks/eks_live_migration/calico.yaml
examples/eks/eks_live_migration/castai.tf
examples/eks/eks_live_migration/deploy.yaml
examples/eks/eks_live_migration/eks-init-script.sh
examples/eks/eks_live_migration/eks.tf
examples/eks/eks_live_migration/main.tf
examples/eks/eks_live_migration/tf.vars.example
examples/eks/eks_live_migration/variables.tf
examples/gke/gke_live_migration/README.MD
examples/gke/gke_live_migration/castai.tf
examples/gke/gke_live_migration/gke.tf
examples/gke/gke_live_migration/init_cos.sh
examples/gke/gke_live_migration/init_ubuntu.sh
examples/gke/gke_live_migration/tf.vars.example
examples/gke/gke_live_migration/variables.tf
examples/gke/gke_live_migration/version.tf
examples/gke/gke_live_migration/vpc.tf

- adding live-migration examples to eks and gke
- examples contains their own readme with details of the setup
- the examples are basically full cluster creation + special node configuration init script

adding live-migration examples

---

README.md
castai/resource_autoscaler.go
docs/resources/autoscaler.md
examples/aks/aks_cluster_arm_template/castai.tf
examples/aks/aks_cluster_autoscaler_policies/castai.tf
examples/eks/eks_cluster_autoscaler_policies/castai.tf
examples/gke/gke_cluster_gitops/castai.tf

This PR deprecates fields from autoscaler_settings:
1. `headroom` and `headroom_spot` - reference this [FAQ section](https://docs.cast.ai/docs/autoscaler-1#can-you-please-share-some-guidance-on-cluster-headroom-i-would-like-to-add-some-buffer-room-so-that-pods-have-a-place-to-run-when-nodes-go-down) for a replacement functionality.
2. `node_constraints` - this field was moved from version 5.x.x and migration was advised.
3. `custom_instances_enabled` this field was moved from version 5.x.x and migration was advised.
4. `spot_instances` this object have now equivalent configuration in default node template, migration was advised from version 5.x.x.
Additionally removed/moved deprecated fields in examples.

feat: deprecate autoscaler policies that were replaced by node templates

---

castai/resource_workload_scaling_policy.go
castai/resource_workload_scaling_policy_order.go
castai/sdk/api.gen.go

**Description**
1. without checking the err code  TF detects state drift during plan, but apply doesn't fail (it passes)
2. We forgot to allow the regex/contains operator on https://github.com/castai/terraform-provider-castai/pull/512

fix: fix allowed rules operators, check response code on policy order changes

---

castai/resource_workload_scaling_policy.go
castai/sdk/api.gen.go

**Description**
Tested with local TF:
```tf
provider "castai" {
api_url   = var.castai_api_url
api_token = var.castai_api_token
}
resource "castai_workload_scaling_policy" "services" {
name              = "services-v4"
cluster_id        = var.castai_gke_cluster_id
apply_type        = "IMMEDIATE"
management_option = "MANAGED"
assignment_rules {
rules {
namespace {
names = ["kube-.*"]
}
}
rules {
workload {
gvk = ["Deployment", "StatefulSet"]
labels_expressions {
key      = "app.kubernetes.io/managed-by"
operator = "Regex"
values   = ["B.*"]
}
}
}
rules {
workload {
gvk = ["Deployment", "StatefulSet"]
labels_expressions {
operator = "Regex"
values   = ["B.*"]
}
}
}
}
cpu {
function = "QUANTILE"
overhead = 0.15
apply_threshold_strategy {
type       = "PERCENTAGE"
percentage = 0.1
}
args …
```

fix: make key optional for labels matcher in assignment rules

---

examples/eks/eks_clusters/castai.tf
examples/eks/eks_clusters/eks.tf

```
│ echo "Cluster is not ready after 10 minutes"
│ exit 1
│ ': exit status 1. Output: Cluster is not ready after 10 minutes
```
We have a dependency problem with eks module and the resource creation must be completed before cast ai module runs
Tested this change and working fine,
`
Apply complete! Resources: 90 added, 0 changed, 0 destroyed.`

chore: fix Cluster is not ready after 10 minutes

---

castai/resource_workload_scaling_policy.go
castai/resource_workload_scaling_policy_test.go
castai/sdk/api.gen.go
castai/sdk/client.gen.go
castai/sdk/mock/client.go
docs/resources/workload_scaling_policy.md

- marking rollout behavior type optional

feat: config option to prefer one-by-one recommendation rollouts

---

castai/sdk/api.gen.go
castai/sdk/client.gen.go
castai/sdk/mock/client.go

Running `make generate-sdk` on the repository because it causes PRs to fail ([example](https://github.com/castai/terraform-provider-castai/pull/568)).

chore: make generate-sdk

---

examples/gke/gke_private_service_connect/README.MD
examples/gke/gke_private_service_connect/castai.tf
examples/gke/gke_private_service_connect/gke.tf
examples/gke/gke_private_service_connect/private-service-connect.tf
examples/gke/gke_private_service_connect/tf.vars.example
examples/gke/gke_private_service_connect/variables.tf
examples/gke/gke_private_service_connect/version.tf
examples/gke/gke_private_service_connect/vpc.tf

Adding a new example that showcases a complete setup of a GKE cluster connecting to Cast AI via Private Service Connect. Going to reference this from public documentation soon.
I was able to `tofu apply` this example without issues:
It can also be `tofu destroy`'ed:
The cluster was successfully created and onboarded to Cast AI:

feat(examples): add GKE example with Private Service Connect
