castai/terraform-provider-castai

castai/resource_castai_gke_cluster.go
castai/resource_castai_gke_cluster_test.go
castai/sdk/api.gen.go
examples/gke_cluster/locals.tf
examples/gke_cluster_zonal/gke.tf
examples/gke_cluster_zonal/locals.tf
examples/gke_cluster_zonal/main.tf
examples/gke_cluster_zonal/variables.tf
examples/gke_cluster_zonal/version.tf
examples/gke_cluster_zonal/vpc.tf

PR for usage in GKE module
https://github.com/castai/terraform-castai-gke-cluster/pull/4

fix(gke): add missing support for GKE zonal clusters

---

castai/resource_castai_eks_cluster.go
castai/sdk/api.gen.go
examples/eks_cluster/eks.tf
examples/eks_cluster/main.tf
examples/eks_cluster/output.tf
examples/eks_cluster/variables.tf
examples/eks_cluster/versions.tf
examples/eks_cluster_assumerole/eks.tf
examples/eks_cluster_assumerole/main.tf
examples/eks_cluster_assumerole/variables.tf
examples/eks_cluster_assumerole/versions.tf
examples/eks_cluster_assumerole/vpc.tf
examples/eks_cluster_webshop/main.tf

Update in module https://github.com/castai/terraform-castai-eks-cluster/pull/14

fix(eks): do not change SGs after first apply

---

.github/workflows/build.yml
Makefile
castai/provider_test.go

Adds 'Acceptance Test' step in Build workflow

feat: add 'Acceptance Test' step to Build workflow

---

castai/resource_castai_autoscaler.go
castai/resource_castai_autoscaler_test.go
castai/sdk/api.gen.go
castai/sdk/client.gen.go
castai/sdk/mock/client.go

fix: log error when updating autoscaler policy

---

examples/eks_cluster_webshop/README.md
examples/eks_cluster_webshop/eks.tf
examples/eks_cluster_webshop/k8s/namespace.yaml
examples/eks_cluster_webshop/versions.tf

Upgrades EKS to 1.23, while testing fixed namespace issue, along with some gaps in the docs.

Demo changes lk

---

castai/resource_node_configuration.go
castai/resource_node_configuration_test.go
castai/sdk/api.gen.go
castai/sdk/client.gen.go
castai/sdk/mock/client.go
docs/resources/node_configuration.md
examples/gke/gke_cluster_autoscaler_policies/castai.tf

- Adding max_pods_per_node in node configuration for GKE provider

GKE max_pods_per_node in node configuration

---

castai/data_source_eks_settings.go

- Add deprecation for field `instance_profile_policies`

Deprecated: instance_profile_policies

---

castai/resource_eks_cluster_test.go
castai/resource_node_configuration.go
castai/resource_node_configuration_test.go
castai/sdk/api.gen.go
docs/resources/node_configuration.md
examples/eks/eks_cluster_autoscaler_polices/castai.tf

- Add support customisation of "imdsV1" in EKS

Add attribute "imdsV1" for EKS

---

go.mod

Exclude vulnerable transient dependency

---

.github/workflows/examples.yml
Makefile
castai/sdk/api.gen.go
castai/sdk/client.gen.go
castai/sdk/client.go
castai/sdk/mock/client.go
examples/eks/eks_cluster_assumerole/vpc.tf
examples/eks/eks_cluster_autoscaler_polices/vpc.tf
examples/eks/eks_cluster_custom_iam/iam.tf
examples/eks/eks_cluster_custom_iam/vpc.tf
examples/eks/eks_cluster_readonly/vpc.tf
examples/eks/eks_cluster_webshop/bucket.tf
examples/eks/eks_cluster_webshop/vpc.tf

- Update VPC package due bug https://github.com/hashicorp/terraform/issues/31730
- Update S3 packages due deprecation of resources

Update eks examples due deprecated modules

---

castai/resource_node_configuration_eks_test.go
castai/resource_node_template_test.go

Fix TF Acceptance test after additional validation for routable subnets was added on server side.

test: fix Acceptance test with providing routable subnets to Node Configurations

---

castai/sdk/api.gen.go
castai/sdk/client.gen.go
castai/sdk/mock/client.go
examples/eks/eks_cluster_optional_readonly/iam.tf

Update eks_cluster_option_readonly IAM permissions to allow import SSH key pairs

Update eks_cluster_option_readonly IAM permissions

---

examples/eks/eks_cluster_assumerole/README.MD
examples/eks/eks_cluster_autoscaler_policies/README.MD
examples/eks/eks_cluster_optional_readonly/README.MD
examples/eks/eks_cluster_readonly/README.MD
examples/eks/eks_clusters/README.MD

making edits to the README on the Example EKS repos to specify which ones are for phase 1 & 2, because some customers having been facing issues differentiating lately.

ReadMe update 

---

castai/sdk/api.gen.go
castai/sdk/client.gen.go
castai/sdk/mock/client.go

chore: sync generated resources

---

castai/const.go
castai/resource_node_template.go
castai/resource_node_template_test.go
docs/resources/node_template.md

Reverts castai/terraform-provider-castai#306

Revert "refactor!: deprecate `compute_optimized` and `storage_optimized` contraints"

---

castai/sdk/api.gen.go

gen: update generated resources

---

castai/resource_node_template.go

The default node template is automatically created in the background with the name default-by-castai. Because of this, Terraform should use an update (PUT) request instead of a create (POST) request when adding the default node template.
This PR adds a check for the template name to avoid 404 errors and ensure clear error messages when custom default node templates are added.
Example custom default template:
```hcl
resource "castai_node_template" "test" {
name       = "test"
cluster_id = "c1f385e7-ec04-4450-95e5-f8b9ca01f159"
is_default = true
is_enabled = true
constraints {
architectures = ["amd64", "arm64"]
}
}
```
New response:
```text
2024-05-22T13:54:18.528+0200 [ERROR] vertex "castai_node_template.test" error: expected status code 200, received: status=400 body={"message":"cannot …
```

fix: add name to default template validation

---

examples/gke/gke_cluster_autoscaler_policies/castai.tf
examples/gke/gke_cluster_existing/castai.tf
examples/gke/gke_cluster_zonal_autoscaler/castai.tf

Depends on https://github.com/castai/terraform-castai-gke-cluster/pull/71

refactor: use `autoscaler_policy_overrides` in examples

---

.github/workflows/doc.yaml
.github/workflows/examples.yml
examples/aks/aks_cluster/variables.tf
examples/aks/aks_cluster_arm_template/variables.tf
examples/aks/aks_cluster_autoscaler_policies/variables.tf
examples/aks/aks_cluster_azure_cni/variables.tf
examples/eks/eks_cluster_access_entries/variables.tf
examples/eks/eks_cluster_assumerole/variables.tf
examples/eks/eks_cluster_autoscaler_policies/variables.tf
examples/eks/eks_cluster_custom_iam/variables.tf
examples/eks/eks_cluster_optional_readonly/variables.tf
examples/eks/eks_cluster_readonly/variables.tf
examples/eks/eks_clusters/variables.tf

just updating the k8s version for AKS and EKS

k8s version update

---

examples/eks/eks_cluster_access_entries/README.MD
examples/eks/eks_cluster_assumerole/README.MD
examples/eks/eks_cluster_autoscaler_policies/README.MD
examples/eks/eks_cluster_custom_iam/README.md
examples/eks/eks_cluster_existing/README.MD
examples/eks/eks_cluster_optional_readonly/README.MD
examples/eks/eks_cluster_readonly/README.MD
examples/eks/eks_clusters/README.MD

Updated information on the variables in the read me file of this example.

Updated information on variables in read me

---

castai/resource_node_configuration.go
docs/resources/node_configuration.md

Add possible values for image family to description.

---

castai/resource_eks_cluster_id.go
castai/resource_eks_cluster_userarn.go
castai/resource_eviction_config.go
docs/resources/eks_clusterid.md
docs/resources/eks_user_arn.md
docs/resources/evictor_advanced_config.md
examples/eks/eks_cluster_existing/castai.tf

Summary:
1. Update resources description 
2. Add explicit dependency for eks example
3. Mark optional arg as required in eviction config

Update resources description & explicit dependency for eks example

---

docs/resources/autoscaler.md
examples/eks/eks_cluster_existing/README.MD
examples/eks/eks_cluster_existing/castai.tf
examples/eks/eks_cluster_existing/outputs.tf
examples/eks/eks_cluster_existing/providers.tf
examples/resources/castai_autoscaler/resource.tf

Change Summary:
Add access entry handling
Restructure folder structure
Add spot template in NT
Update README

Add access entry handling & restructure folder

---

examples/gke/gke_cluster_existing/castai.tf
examples/gke/gke_cluster_existing/providers.tf
examples/gke/gke_cluster_gitops/README.md
examples/gke/gke_cluster_gitops/castai.tf

Summary:
1. Add Spot NT
2. Fix Gitops Approach
3.Enhance README

Update GKE examples

---

README.md
examples/eks/eks_cluster_gitops/README.md
examples/gke/gke_cluster_existing/castai.tf
examples/gke/gke_cluster_gitops/README.md
examples/gke/gke_cluster_gitops/castai.tf

Summary:
Fix helm installation for castai-agent
Update pod-pinner & evictor replica count
Fix spot template label

Fix helm commands

---

examples/aks/aks_cluster_existing/castai.tf
examples/aks/aks_cluster_existing/providers.tf
examples/aks/aks_cluster_existing/variables.tf
examples/aks/aks_cluster_gitops/README.md
examples/aks/aks_cluster_gitops/castai.tf
examples/aks/aks_cluster_gitops/providers.tf

Summary:
Fix Azure provider
Add Spot NT
Fix Gitops Approach
Enhance README

Fix gitops & existing cluster example

---

examples/eks/eks_cluster_existing/README.MD
examples/eks/eks_cluster_existing/tf.vars.example
examples/eks/eks_cluster_gitops/README.md
examples/eks/eks_cluster_gitops/castai.tf
examples/eks/eks_cluster_gitops/tf.vars.example

Summary:
1. Updated readme with aws profile setting 
2. Housekeeping for unused vars

Update readme & Gitops housekeeping

---

castai/resource_organization_group.go
castai/sdk/api.gen.go

Due to the recent changes in https://castai.atlassian.net/browse/WIRE-943

NOJIRA: fix organization group resource

---

castai/resource_autoscaler.go
castai/sdk/api.gen.go
docs/resources/autoscaler.md

deprecate custom_instances_enabled in policy in favor of node_template

---

castai/resource_rebalancing_schedule.go

This PR changes the default node sorting algorithm for scheduled rebalancing to Highest Utilized Resource Price.

feat: change default sorting algo in scheduled rebalancing

---

castai/resource_node_template.go
castai/resource_node_template_test.go
docs/resources/node_template.md

Added missing node template constraints.
Additionally, updated generated API client and handled pointer dereference panic on role bindings.

fix: missing node template constraints

---

.github/workflows/build.yml
castai/resource_workload_scaling_policy_test.go
castai/sdk/api.gen.go
docs/resources/node_template.md

Install workload-autoscaler. Needed for WOOP scaling policy tests.

Install workload-autoscaler

---

castai/resource_node_template.go
castai/resource_node_template_test.go
castai/sdk/api.gen.go
castai/sdk/client.gen.go
castai/sdk/mock/client.go
docs/resources/node_template.md

Note: e2e test for the node template was passing on first launch with some other tests failing. Hence, it seems like a setup problem, not a problem with the test or the feature.

LIVE-478: feat: add clm_enabled to node_template resource

---

examples/aks/aks_cluster/variables.tf
examples/aks/aks_cluster_arm_template/variables.tf
examples/aks/aks_cluster_autoscaler_policies/variables.tf
examples/aks/aks_cluster_azure_cni/variables.tf
examples/eks/eks_cluster_access_entries/variables.tf
examples/eks/eks_cluster_assumerole/variables.tf
examples/eks/eks_cluster_autoscaler_policies/variables.tf
examples/eks/eks_cluster_custom_iam/variables.tf
examples/eks/eks_cluster_ipv6/variables.tf
examples/eks/eks_cluster_live_migration/variables.tf
examples/eks/eks_cluster_optional_readonly/variables.tf
examples/eks/eks_cluster_readonly/variables.tf
examples/eks/eks_cluster_with_security/variables.tf
examples/eks/eks_cluster_with_security_runtime_rules/variables.tf
examples/eks/eks_clusters/variables.tf

Updating K8s versions for AKS and EKS

Updating K8s versions

---

castai/resource_enterprise_group_test.go
castai/sdk/api.gen.go
castai/sdk/organization_management/api.gen.go

In this PR I am regenerating client for enterprises, and adjusting modified parameter

fix: regenerate enterprise client to fix tests
